project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "notebooks/"

website:
  # title: "<a href='https://youtu.be/fn1R-5p_j5c?si=f0ZoaDm-FcT3uIwH'>not a machine</a>"
  title: Taming the data
  # favicon: note
  site-url: https://newgnart.github.io
  repo-url: https://github.com/newgnart
  # repo-actions: [edit, issue]
  page-navigation: true
  search: true
  page-footer:
    left: |
      Built with [Quarto](https://quarto.org)
    right:
      - icon: github
        href: https://github.com/newgnart
        aria-label: GitHub
      - icon: telegram
        href: https://t.me/newgnart
        aria-label: Telegram
  navbar:
    background: light
    search: true
    collapse-below: lg

    # right:
      # - text: "Home"
      #   href: https://newgnart.github.io/blog/
      # - text: "Stablecoins"
      #   href: /#category=stablecoins



format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    highlight-style: github
    code-fold: false
    code-tools: false
    fig-responsive: true
    fig-format: retina
    fig-dpi: 144
    fig-asp: 1.618
    fig-width: 8
    fig-height: 5
    fig-align: center
    fig-pos: H
    fig-cap-location: bottom
    fig-subcap-location: bottom
    fig-link: false
    fig-alt: null
    fig-env: figure
    fig-scap: null
    fig-lp: null
    fig-float: true
    fig-float-placement: H
    fig-float-reference: fig
    fig-float-caption: true
    fig-float-caption-location: bottom
    fig-float-caption-style: null
    fig-float-caption-sep: ": "
    fig-float-caption-prefix: "Figure "
    fig-float-caption-suffix: "."
    fig-float-caption-prefix-singular: "Figure "
    fig-float-caption-prefix-plural: "Figures "
    fig-float-caption-sep-singular: ": "
    fig-float-caption-sep-plural: ": "
    fig-float-caption-suffix-singular: "."
    fig-float-caption-suffix-plural: "."
    fig-float-caption-style-singular: null
    fig-float-caption-style-plural: null
    